name: "Deploy via SSH"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on PROD server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.AWS_REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.AWS_REMOTE_SERVER_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            pwd
